PORT = 5000
PUBLIC_PORT = 6718

FRONTEND_URL = 'https://matuspilnan.github.io/varpivo-elm'

RECIPES_DIR = 'recipes'
SCALE_CALIBRATION_FILE = 'scale_calibration.json'
SCALE_CALIBRATION_ERROR_THRESHOLD = 50
SCALE_INIT_TIMEOUT = 5
HEATER_RELAY_GPIO = 24

DEFAULT_MASH_STEP_TIME = 60
BREW_SESSION_CODE_HEADER = 'Authorization'
BREW_SESSION_CODE_LENGTH = 6

CHECKPOINT_DIR = 'shelf'
RECIPE_CHECKPOINT_FILE = "shelf.page"
KETTLE_CHECKPOINT_FILE = "shelf.kettle"
SECURITY_CHECKPOINT_FILE = "shelf.security"

NDEF_FILE = 'out/ndef_file'
SECURITY_CODE_FONT_FILE = '/usr/share/fonts/truetype/noto/NotoMono-Regular.ttf'
SCREEN_CYCLE_INTERVAL = 120
DISPLAY_I2C_PORT = 0
DISPLAY_I2C_ADDRESS = 0x3C

BUTTON_NEXT_GPIO = 21
BUTTON_PREV_GPIO = 20

BUZZER_GPIO = 26
BUZZER_DELAY = 0.5

LOG_FOLDER = 'logs'
LOG_FILE = 'varpivo.log'
