PORT = 5000
PUBLIC_PORT = 6718

FRONTEND_URL = 'https://matuspilnan.github.io/varpivo-elm'

RECIPES_DIR = 'recipes'
SCALE_CALIBRATION_FILE = 'scale_calibration.json'
SCALE_CALIBRATION_ERROR_THRESHOLD = 50
HEATER_RELAY_GPIO = 24

DEFAULT_MASH_STEP_TIME = 60
BREW_SESSION_CODE_HEADER = 'Authorization'
BREW_SESSION_CODE_LENGTH = 6

CHECKPOINT_DIR = 'shelf'
RECIPE_CHECKPOINT_FILE = "shelf.page"
KETTLE_CHECKPOINT_FILE = "shelf.kettle"
SECURITY_CHECKPOINT_FILE = "shelf.security"
