RECIPES_DIR = 'recipes'
SCALE_CALIBRATION_FILE = 'scale_calibration.json'
SCALE_CALIBRATION_ERROR_THRESHOLD = 50
HEATER_RELAY_GPIO = 24

DEFAULT_MASH_STEP_TIME = 60

CHECKPOINT_DIR = 'shelf'
RECIPE_CHECKPOINT_FILE = "shelf.page"
KETTLE_CHECKPOINT_FILE = "shelf.kettle"

DISPLAY_CYCLE_INTERVAL = 120

BUTTON_NEXT_GPIO = 21
BUTTON_PREV_GPIO = 20
